### ISSUE TITLE
process.exit from inside an async function

### ISSUE THREAD

**Issue by jasnell** [covidgreen/covid-green-backend-api#10]
The migrate.js script (https://github.com/covidgreen/covid-green-backend-api/blob/current/lib/migrate.js#L33) includes an async function that calls `process.exit(0)` or `process.exit(1)` explicitly. This is a bit unusual. Opening this as a potential good first issue for someone to jump in.

**Comment by jasnell** [comment]
Note that changing this will have an impact on the test here: https://github.com/covidgreen/covid-green-backend-api/blob/current/lib/migrate.test.js

**Comment by mikegwhit** [comment]
Grabbing this one.. looks like I cannot assign myself or otherwise designate assignee.

**Comment by ShaunBaker** [comment]
The use of `process.exit` has come from similar usage from previous projects, for example, in Kubernetes when these migrations are run as a job prior to deploy/start of pods running application code.

They require correct process exit codes to determine whether they did indeed succeed or fail etc.

FYI
