### ISSUE TITLE
Some of the environment values used need details.

### ISSUE THREAD

**Issue by Shashi-GS** [covidgreen/covid-green-backend-api#103]
Hi,

 could you please help me to from where these information has to be picked up and configured?

DEVICE_CHECK_KEY_ID=
DEVICE_CHECK_KEY=
DEVICE_CHECK_TEAM_ID=
DEVICE_CHECK_PACKAGE_NAME=
DEVICE_CHECK_PACKAGE_DIGEST=
DEVICE_CHECK_CERTIFICATE_DIGEST=
DEVICE_CHECK_ROOT_CA=
DEVICE_CHECK_TIME_DIFF_THRESHOLD_MINS=10
DEVICE_CHECK_RECAPTCHA_SECRET=

due to this. when I do a register with nonce, its throwing below error

{"code": "200", "error": "Internal Server Error", "message": "CA missing or invalid", "statusCode": 500}

please help us. it would be really helpful.

--
Cheers,
Shashi

**Comment by colmharte** [comment]
DEVICE_CHECK_KEY_ID - iOS only - You get this from the AppStore when creating a device check key
DEVICE_CHECK_TEAM_ID - iOS only - Also comes from the appstore, its your appstore team id
DEVICE_CHECK_PACKAGE_NAME - Android Only - the package name of your app (optional)
DEVICE_CHECK_PACKAGE_DIGEST - Android Only  - The SHA256 digest for your APK (optional)
DEVICE_CHECK_CERTIFICATE_DIGEST - Android Only - The SHA256 digest of the cert used to sign the APK (optional)
DEVICE_CHECK_ROOT_CA - Android Only - Used to validate the signing certificate as a valid google cert if using appstore signing - https://pki.goog/
DEVICE_CHECK_TIME_DIFF_THRESHOLD_MINS - Threshold in minutes used to detect when device date/time is incorrect
DEVICE_CHECK_RECAPTCHA_SECRET - Only needed if your app supports fallback to using a recpatcha if safetynet / devicecheck fails (optional)
