### ISSUE TITLE
Why is there a default nonce value here?

### ISSUE THREAD

**Issue by davidgtonge** [covidgreen/covid-green-backend-api#110]
Would be good to use a named variable to help those reading the code understand

https://github.com/covidgreen/covid-green-backend-api/blob/211f61c9d4615338a97ce74fe73a2c8cd713719b/lib/routes/register/index.js#L178

**Comment by colmharte** [comment]
This is used during testing when we allow calls to the refresh end point that do not contain a refresh end token. `options.security.allowNoToken` must be true to execute this logic

**Comment by davidgtonge** [comment]
ok thanks for the explaination
