### ISSUE TITLE
TODO: Document the REST API

### ISSUE THREAD

**Issue by jasnell** [covidgreen/covid-green-backend-api#12]
We need to include documentation of the API endpoints, including expected inputs/outputs/errors. While some of the details of what each does will need some deeper understanding of the code, a good first issue for a new contributor could be scaffolding out some docs derived from the route definitions

**Comment by mikegwhit** [comment]
Addressed by https://github.com/covidgreen/covid-green-backend-api/pull/11

**Comment by dennisgove** [comment]
Complete
