### ISSUE TITLE
Database migration doesn't appear to be running as expected

### ISSUE THREAD

**Issue by dennisgove** [covidgreen/covid-green-backend-api#22]
If I follow the steps in the README to initialize a new system I end up with a running database but the migrations are not run.

```bash
$> npm install
$> npm run create:env
$> npm run db:up
$> npm run db:migrate
```

The process fails on https://github.com/covidgreen/covid-green-backend-api/blob/current/lib/migrate.js#L24 and does not indicate any failure occurred. It just silently ends with a 0 return code.

**Comment by dennisgove** [comment]
The docker-compose logs don't show any attempt being made to run migrations

```bash
$> docker-compose logs -f
Attaching to contact-tracing-db
contact-tracing-db    | 2020-08-05 21:24:39.871 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
contact-tracing-db    | 2020-08-05 21:24:39.871 UTC [1] LOG:  listening on IPv6 address "::", port 5432
contact-tracing-db    | 2020-08-05 21:24:39.874 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
contact-tracing-db    | 2020-08-05 21:24:39.888 UTC [18] LOG:  database system was shut down at 2020-08-05 21:23:43 UTC
contact-tracing-db    | 2020-08-05 21:24:39.892 UTC [1] LOG:  database system is ready to accept connections
```

**Comment by ShaunBaker** [comment]
As a sanity check - you do not have another Postgres instance running on your host/port that it is connecting to?

**Comment by dennisgove** [comment]
I don't have any other instances running, and the instance that is running is listening in the expected port.

```bash
$> docker ps --format '{{.Image}}\t{{.Ports}}\t{{.Names}}'
postgres:10.4-alpine	0.0.0.0:5432->5432/tcp	       contact-tracing-db
```

My `.env` file contains these settings for the database
```
DB_HOST=localhost
DB_READ_HOST=localhost
DB_PORT=5432
DB_USER=contact_tracing
DB_PASSWORD=contact_tracing
DB_DATABASE=contact_tracing
DB_SSL=false
```

Also if the migration was completing, either in error or in success I'd expect one of these log lines to be printed, but neither are. https://github.com/covidgreen/covid-green-backend-api/blob/current/lib/migrate.js#L32-L36

And as a sanity check of my own I added log lines to see how far it's getting and it only gets as far as printing out `2`.

```javascript
async function migrateSchema() {
  console.log('running migration')
  try {
    const config = await getConfig()
    console.log('1')
    const postgrator = getPostgratorInstance(config)
    console.log('2')
    const result = await postgrator.migrate()
    console.log('3')
    if (result.length === 0) {
      console.log('4')
      console.log(
        'No migrations run for schema "public". Already at the latest one.'
      )
      console.log('5')
    }
    console.log('6')
    console.log('Migration done')
    console.log('7')
    process.exit(0)
  } catch (error) {
    console.log('8')
    console.error(error)
    console.log('9')
    process.exit(1)
  }
}
```
```bash
$> npm run db:migrate

> exposure-notification-api@1.0.0 db:migrate /Users/dgove1/dev/covid/covid-green-backend-api
> node lib/migrate.js

running migration
1
2
$>
```

**Comment by dennisgove** [comment]
Just to confirm the rcode, after running `npm run db:migrate`
```bash
$> echo $?
0
```

**Comment by jasnell** [comment]
@dennisgove ... could you modify migrate.js just a bit to determine if the `Promise` returned here (https://github.com/covidgreen/covid-green-backend-api/blob/current/lib/migrate.js#L41) actually resolves? 

I suspect that the rcode that you're seeing here is from the `npm run db:migrate` call and not from the actual run of `lib/migrate.js`, which, as I point out in issue #10 is not properly exiting.

**Comment by ShaunBaker** [comment]
This appears to be an issue local to @dennisgove.

With a fresh clone and following the command steps in the readme it is functioning as expected.

**Comment by jasnell** [comment]
Interesting... ok, quick digging shows that there's likely a bug within `postgrator` somewhere then. A failure in `const result = await postgrator.migrate()` appears to cause the process to exit rather than properly resolving or rejecting. Definitely not ideal.

**Comment by dennisgove** [comment]
I've entered https://github.com/covidgreen/covid-green-backend-api/pull/25 to help mitigate (though not fix) this issue. It adds support for running everything inside Docker containers will known versions of `node`.

**Comment by jasnell** [comment]
It would likely be a good idea to add a comment into migrate.js that describes the basic issue here... Specifically, something that indicates that the `await postgrator.migrate()` call can cause the process to exit without a proper error and what that likely means.

**Comment by dennisgove** [comment]
> @dennisgove ... could you modify migrate.js just a bit to determine if the `Promise` returned here (https://github.com/covidgreen/covid-green-backend-api/blob/current/lib/migrate.js#L41) actually resolves?
> 
> I suspect that the rcode that you're seeing here is from the `npm run db:migrate` call and not from the actual run of `lib/migrate.js`, which, as I point out in issue #10 is not properly exiting.

Changing that to see if the promise resolves does show a promise.

```
if (require.main === module) {
  const result = migrateSchema()
  console.log(result)
}
```

```bash
$> npm run db:migrate

> exposure-notification-api@1.0.0 db:migrate /Users/dgove1/dev/covid/covid-green-backend-api
> node lib/migrate.js

Promise { <pending> }
```

**Comment by jasnell** [comment]
You'd want something like

```js
migrateSchema().then(() => console.log('ok'))
```

In my local testing here, it does not resolve when the error is hit. Everything is pointing at `postgrator` causing the process to exit prematurely when it fails to get the database connection.

**Comment by dennisgove** [comment]
Confirm that this line does not result in `ok` being printed to the console.

```js
migrateSchema().then(() => console.log('ok'))
```

**Comment by dennisgove** [comment]
> It would likely be a good idea to add a comment into migrate.js that describes the basic issue here... Specifically, something that indicates that the `await postgrator.migrate()` call can cause the process to exit without a proper error and what that likely means.

Have added such a comment to the PR.

**Comment by mikegwhit** [comment]
I'm not 100% sure I noted this already, but upgrading our `pg` dependency to 8.3.0 fixed this for me.  This should have been merged by now in a prior PR, so this issue may be worth re-testing with latest version utilizing 8.3.0
