### ISSUE TITLE
Nominating Dennis Gove as a contributor

### ISSUE THREAD

**Issue by jasnell** [covidgreen/covid-green-backend-api#7]
@covidgreen/members ... I wanted to nominate @dennisgove as a contributor. If I'm not mistaken, they're with bloomberg (@dennisgove can you confirm?). There's been a number of commits across multiple repos, adding as a member will give commit rights to all of the main repos.

Please weigh in with either a 👍🏻 or 👎🏻 (if you have any objections)

**Comment by dennisgove** [comment]
Yes, I am with Bloomberg.

And thank you for the nomination!

**Comment by jasnell** [comment]
If there are no objections by Monday I'll add @dennisgove to the @covidgreen/members team! 

(@covidgreen/core ... at some point we should come up with an onboarding process)

**Comment by jasnell** [comment]
Ok! @dennisgove, I've added you to the @covidgreen/members team which gives you write access to the repository. Please be sure to review the CONTRIBUTING.md guide (which, right now is a rough starter that likely will evolve once we continue to get bootstrapped) and the Code of Conduct.

**Comment by jasnell** [comment]
When you get a moment, please open a PR that adds yourself to the list of Contributors in the README.md in each of the project repos... there's a good handful of them... we'll work on having a single master list later
